import style from "./sass/style.scss";
import createElement from "./js/screens/createElement.js";
import showScreen from "./js/screens/showScreen.js";
import { returnGreeting, main, clearMain } from "./js/screens/main.js";
main();
import showIntro from "./js/screens/intro.js";
import { showGreeting, greetingScreen } from "./js/screens/greeting.js";
import showRules from "./js/screens/rules.js";
import { getGameOneScreenTemplate, showGameOneScreen } from "./js/screens/game-1.js";
import { getGameTwoScreenTemplate, showGameTwoScreen } from "./js/screens/game-2.js";
import { getGameThreeScreenTemplate, showGameThreeScreen } from "./js/screens/game-3.js";
import { showStats, getFailScreenTemplate, getStatsScreenTemplate } from "./js/screens/stats.js";