import style from "./sass/style.scss";
import createElement from "./js/screens/createElement.js";
import showScreen from "./js/screens/showScreen.js";
import main from "./js/screens/main.js";
main();
import showIntro from "./js/screens/intro.js";
import { showGreeting } from "./js/screens/greeting.js";
import rulesScreen from "./js/screens/rules.js";
import { showGameOneScreen } from "./js/screens/game-1.js";
import gameTwoScreen from "./js/screens/game-2.js";
import gameThreeScreen from "./js/screens/game-3.js";
import statsScreen from "./js/screens/stats.js";